# Generated by Django 4.2 on 2025-12-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wof_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGoodsMaster',
            fields=[
                ('ItemCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
