# Generated by Django 4.2 on 2025-12-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wof_app', '0002_finishedgoodsmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('EmployeeName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblEmployeeMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LineMaster',
            fields=[
                ('LineName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Product', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tblLineMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperationMaster',
            fields=[
                ('OperationName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Product', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tblProductionOperationMaster',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='finishedgoodsmaster',
            options={'managed': False},
        ),
    ]
