# Generated by Django 4.2 on 2025-12-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wof_app', '0003_employeemaster_linemaster_operationmaster_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='finishedgoodsmaster',
            table='tblFinishedGoodsMaster',
        ),
    ]
